require 'shokkenki/consumer/core_ext/string'
require 'shokkenki/consumer/core_ext/hash'
require 'shokkenki/consumer/core_ext/regexp'
require 'shokkenki/consumer/core_ext/symbol'
require 'shokkenki/consumer/core_ext/numeric'